// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJsRhAhm2r9P2TWaFrfkSKRxB01_2YAj4',
    appId: '1:617027030306:web:bd65883bc2a7cf18f3a97b',
    messagingSenderId: '617027030306',
    projectId: 'cineva-bb3b9',
    authDomain: 'cineva-bb3b9.firebaseapp.com',
    storageBucket: 'cineva-bb3b9.firebasestorage.app',
    measurementId: 'G-2N4SF04MKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdzPB-0nRmSGdW30YY-0VuJzFd1pRXQsY',
    appId: '1:617027030306:android:464823be39a9cafcf3a97b',
    messagingSenderId: '617027030306',
    projectId: 'cineva-bb3b9',
    storageBucket: 'cineva-bb3b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfJUvWVAxc8RndK3G5oaH5-miom364meU',
    appId: '1:617027030306:ios:aff9222e977901d8f3a97b',
    messagingSenderId: '617027030306',
    projectId: 'cineva-bb3b9',
    storageBucket: 'cineva-bb3b9.firebasestorage.app',
    iosClientId: '617027030306-s9ot3s1q4pjllinfjmnp9v0ggkjritl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfJUvWVAxc8RndK3G5oaH5-miom364meU',
    appId: '1:617027030306:ios:aff9222e977901d8f3a97b',
    messagingSenderId: '617027030306',
    projectId: 'cineva-bb3b9',
    storageBucket: 'cineva-bb3b9.firebasestorage.app',
    iosClientId: '617027030306-s9ot3s1q4pjllinfjmnp9v0ggkjritl7.apps.googleusercontent.com',
    iosBundleId: 'com.example.practiceUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJsRhAhm2r9P2TWaFrfkSKRxB01_2YAj4',
    appId: '1:617027030306:web:b03b57f88bdfc5f7f3a97b',
    messagingSenderId: '617027030306',
    projectId: 'cineva-bb3b9',
    authDomain: 'cineva-bb3b9.firebaseapp.com',
    storageBucket: 'cineva-bb3b9.firebasestorage.app',
    measurementId: 'G-LTGZ1BRYP4',
  );
}
